sudo: 'required'

services:
  - 'docker'

script:
  - docker build -f Dockerfile -t simplifi/docker-presto:latest .
  - docker build -f Dockerfile -t simplifi/docker-presto:${TRAVIS_TAG} .
  - docker run simplifi/docker-presto:latest /usr/lib/presto/bin/launcher --help

before_deploy:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ;

# Deploy to Docker Hub (only for tags on master)
deploy:
  # Pushes the latest tag for master branch
  - provider: script
    script: bash docker push simplifi/docker-presto:latest ;
    on:
      tags: false
      branch: master
      repo: simplifi/docker-presto
  # Pushes the versioned tag for a tag
  - provider: script
    script: bash docker push simplifi/docker-presto:${TRAVIS_TAG} ;
    on:
      tags: true
      branch: master
      repo: simplifi/docker-presto
