sudo: required

language: minimal

services:
  - docker

env:
  - VERSION=316
  - VERSION=317 ISLATEST=1

before_script:
  - env | sort

script:
  - docker build --build-arg PRESTO_VERSION=${VERSION} -t simplifi/docker-presto .
  - docker tag simplifi/docker-presto simplifi/docker-presto:${VERSION}
#  - if [ -n "${ISLATEST:+1}" ]; then
#      docker tag simplifi/docker-presto simplifi/docker-presto:latest;
#    fi
  - docker run simplifi/docker-presto:${VERSION} /usr/lib/presto/bin/launcher --help

after_script:
  - docker images

before_deploy:
  - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ;

# Deploy to Docker Hub
deploy:
  # Always push the versioned tag
  - provider: script
    script: bash docker push simplifi/docker-presto:${VERSION} ;
    on:
      branch: master
      repo: simplifi/docker-presto

  # Only push the latest tag if this is the latest version
  - provider: script
    script: bash docker push simplifi/docker-presto:latest ;
    on:
      branch: master
      repo: simplifi/docker-presto
      condition: $ISLATEST = 1
